import java.util.*;
public class bubble_sort{
    public static void sort(int arr[]){

        for(int i=0;i<arr.length-1;i++) {
            int swap=0;
            for (int j = 0; j <arr.length-1- i; j++) {

                if (arr[j] > arr[j + 1]) {
                    int temp;
                    temp = arr[j];
                    arr[j] = arr[j + 1];


                    arr[j + 1] = temp;
                    swap++;
                }
            }
                if(swap==0){
                    break;
                }

        }
          /*  for(int i=0;i<arr.length;i++) {
                System.out.println(arr[i]);
            }
            */


    }
    public static void main(String[] args){

        int repeat=0;
        long time[]=new long[30];//array for storing time

         int arr[]=new int[10000];//the number of elements that are sorted are 10000

         while(repeat<30) {
             Random random=new Random(System.currentTimeMillis());
             for(int i=0;i<arr.length;i++){
                 int k=random.nextInt(0,999999);
                 arr[i]=k;//all number generated by random generator are stored in a form of array
             }
             long begin = System.currentTimeMillis();//begin time
             sort(arr);//if all number store in arr then it time to sort it so we pass our array in sort function
             long end = System.currentTimeMillis();//end time
             time[repeat] = end - begin;
             System.out.println(time[repeat]);
             repeat++;
         }

     }
    }

